# Generated by Django 4.0.4 on 2022-06-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlosblog', '0003_alumnos_delete_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('trabajo', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Examenes',
        ),
    ]
